networks:
  WSO2_enviroment:
services:
  wso2-server:
    build:
      context: .
      dockerfile: .Dockerfile
    ports:
      - 9443:9443
    volumes:
      - ./wso2is-7.1.0:/usr/src/myapp
    container_name: WSO2_enviroment_server
    networks:
      - WSO2_enviroment
  postgres:
    image: "postgres:latest"
    restart: always
    volumes:
      - postgre_WSO2_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: wso2-pg-admin
      POSTGRES_PASSWORD: pgadmin4
      POSTGRES_DB: wso2db
    ports:
      - "5432:5432"
    container_name: WSO2_postgre
    networks:
      - WSO2_enviroment
  wso2-front:
    build:
      context: ./asgardeo
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - "./asgardeo:/usr/src/app"
    container_name: WSO2_enviroment_server_front
    networks:
      - WSO2_enviroment
volumes:
  postgre_WSO2_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/volumes/WSO2POSTGRE
